# NexT Theme Configuration
# Scheme: Muse | Mist | Pisces | Gemini
scheme: Gemini

# Dark Mode
darkmode: true

# Site Information
avatar:
  url: /images/avatar.gif
  rounded: true
  rotated: false

# Code Highlight
codeblock:
  theme:
    light: default
    dark: stackoverflow-dark
  prism:
    light: prism
    dark: prism-dark
  copy_button:
    enable: true
    style: flat

# Social Links
social:
  GitHub: https://github.com/ || fab fa-github
  E-Mail: mailto:yourname@gmail.com || fa fa-envelope

# Menu
menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
